# Generated by Django 3.2.16 on 2023-02-25 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        ('mealplanning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='recipes',
            field=models.ManyToManyField(blank=True, to='recipes.Recipe'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='meal_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 25, 16, 34, 49, 908433), unique=True),
        ),
    ]
