# Generated by Django 3.2.16 on 2023-02-26 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanning', '0002_auto_20230225_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='meal_date',
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='date',
            field=models.DateField(default=datetime.date(2023, 2, 26), unique=True),
        ),
    ]
