# Generated by Django 3.2.18 on 2023-03-04 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanning', '0003_auto_20230226_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='date',
            field=models.DateField(default=datetime.date(2023, 3, 4), unique=True),
        ),
    ]
